# Generated by Django 5.2.7 on 2025-10-29 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='enterpets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=255)),
                ('Age', models.IntegerField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('any_injuries', models.CharField(choices=[('Yes', 'yrs'), ('No', 'no')], default='No', max_length=4)),
                ('describe_if_of_injury_if_there', models.CharField(max_length=255)),
            ],
        ),
    ]
