# Generated by Django 5.2.7 on 2025-10-31 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petadoption', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='adoptionform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.IntegerField(max_length=99)),
                ('why_you_wanna_adopt', models.CharField(max_length=1000)),
                ('do_you_have_any_experince_before_with_animals', models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], default='Yes', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('reject', 'reject')], default='pending', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='enterpets',
            name='specie',
            field=models.CharField(choices=[('Dog', 'dog'), ('Cat', 'cat'), ('turtle', 'turtle'), ('bird', 'bird')], default='dog', max_length=100),
        ),
        migrations.AlterField(
            model_name='enterpets',
            name='Age',
            field=models.IntegerField(choices=[('Dog', 'dog'), ('Cat', 'cat'), ('turtle', 'turtle'), ('bird', 'bird')], default='unkown', max_length=100),
        ),
        migrations.AlterField(
            model_name='enterpets',
            name='any_injuries',
            field=models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], default='No', max_length=4),
        ),
    ]
