# Generated by Django 5.2.7 on 2025-10-31 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petadoption', '0002_adoptionform_enterpets_specie_alter_enterpets_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionform',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='enterpets',
            name='Age',
            field=models.IntegerField(choices=[('Dog', 'dog'), ('Cat', 'cat'), ('turtle', 'turtle'), ('bird', 'bird')], default='unkown'),
        ),
    ]
