# Generated by Django 5.2.7 on 2025-10-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petadoption", "0003_alter_adoptionform_age_alter_enterpets_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="enterpets",
            name="breed",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="enterpets",
            name="color",
            field=models.CharField(default="Unknown", max_length=50),
        ),
    ]
