# Generated by Django 5.2.7 on 2025-10-31 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petadoption', '0004_enterpets_breed_enterpets_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpets',
            name='Age',
            field=models.IntegerField(default=0),
        ),
    ]
