# Generated by Django 5.2.7 on 2025-10-31 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petadoption', '0005_alter_enterpets_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionform',
            name='reasons',
            field=models.CharField(default='no reason provided', max_length=1200),
        ),
    ]
