# Generated by Django 5.2.7 on 2025-11-22 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petadoption', '0006_adoptionform_reasons'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptionform',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='adoptionform',
            name='last_name',
        ),
        migrations.AddField(
            model_name='adoptionform',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adoption_requests', to='petadoption.enterpets'),
        ),
        migrations.AddField(
            model_name='adoptionform',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adoption_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
