# Generated by Django 5.2.7 on 2025-11-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petadoption', '0007_remove_adoptionform_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionform',
            name='do_you_have_any_experince_before_with_animals',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='Yes', max_length=100),
        ),
        migrations.AlterField(
            model_name='enterpets',
            name='any_injuries',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='No', max_length=4),
        ),
    ]
