# Generated by Django 5.2.7 on 2025-11-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petadoption', '0008_alter_adoptionform_do_you_have_any_experince_before_with_animals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpets',
            name='any_injuries',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=4),
        ),
    ]
