# Generated by Django 5.2.7 on 2025-11-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petadoption', '0009_alter_enterpets_any_injuries'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterpets',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
