# Generated by Django 5.2.8 on 2025-11-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petadoption", "0010_enterpets_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enterpets",
            name="specie",
            field=models.CharField(
                choices=[
                    ("Dog", "dog"),
                    ("Cat", "cat"),
                    ("turtle", "turtle"),
                    ("bird", "bird"),
                    ("Rabbit", "rabbit"),
                ],
                default="dog",
                max_length=100,
            ),
        ),
    ]
