# Generated by Django 5.2.8 on 2025-11-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petadoption", "0011_alter_enterpets_specie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enterpets",
            name="describe_if_of_injury_if_there",
            field=models.CharField(default=" ", max_length=255),
        ),
        migrations.AlterField(
            model_name="enterpets",
            name="description",
            field=models.CharField(default=" ", max_length=1000),
        ),
    ]
