# Generated by Django 5.2.8 on 2025-12-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petadoption', '0012_alter_enterpets_describe_if_of_injury_if_there_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterpets',
            name='is_adopted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='enterpets',
            name='specie',
            field=models.CharField(choices=[('Dog', 'dog'), ('Cat', 'cat'), ('Turtle', 'turtle'), ('Bird', 'bird'), ('Rabbit', 'rabbit')], default='dog', max_length=100),
        ),
    ]
