# Generated by Django 6.0 on 2025-12-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petadoption", "0013_enterpets_is_adopted_alter_enterpets_specie"),
    ]

    operations = [
        migrations.CreateModel(
            name="PetFood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("brand", models.CharField(max_length=100)),
                (
                    "food_type",
                    models.CharField(
                        choices=[
                            ("dry", "Dry Food"),
                            ("wet", "Wet Food"),
                            ("treat", "Treat"),
                        ],
                        max_length=10,
                    ),
                ),
                ("suitable_for", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="petfood/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("species", models.CharField(max_length=50)),
                ("age", models.IntegerField()),
                (
                    "recommended_food",
                    models.ManyToManyField(
                        blank=True, related_name="pets", to="petadoption.petfood"
                    ),
                ),
            ],
        ),
    ]
