# Generated by Django 6.0 on 2025-12-13 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petadoption", "0014_petfood_pet"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Pet",
        ),
    ]
