# Generated by Django 6.0 on 2025-12-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petadoption", "0015_delete_pet"),
    ]

    operations = [
        migrations.AddField(
            model_name="petfood",
            name="buy_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
