# Generated by Django 6.0 on 2025-12-13 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petadoption", "0016_petfood_buy_link"),
    ]

    operations = [
        migrations.RenameField(
            model_name="petfood",
            old_name="brand",
            new_name="brand_name",
        ),
        migrations.RemoveField(
            model_name="petfood",
            name="name",
        ),
    ]
