# Generated by Django 6.0 on 2025-12-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petadoption", "0017_rename_brand_petfood_brand_name_remove_petfood_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="petfood",
            name="image",
            field=models.CharField(
                blank=True, default="AnimalLife.jpg", max_length=100
            ),
        ),
    ]
