# Generated by Django 6.0 on 2025-12-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petadoption", "0018_alter_petfood_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="petfood",
            name="image",
            field=models.CharField(
                blank=True,
                default="static/petfood_pictures/AnimalLife.jpg",
                max_length=100,
            ),
        ),
    ]
