# Generated by Django 6.0 on 2025-12-16 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petadoption', '0019_alter_petfood_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petfood',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
